### ISSUE TITLE
Allow specifying which Searx instance to use instead of only searx.me

### ISSUE THREAD

**Issue by Mikaela** [horstderheld/limnoria-searx#3]
As it's FOSS and anyone could run their own instance, it would be nice if there was option for setting the instance to use instead of hardcoding searx.me.

**Comment by lodriguez** [comment]
do you have a link to another instance? added that option, but I would like to try it with another url

**Comment by Mikaela** [comment]
https://github.com/asciimoo/searx/wiki/Searx-instances

night
